"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$aws\
$gcloud\
[](fg:color_blue bg:color_purple)\
$kubernetes\
[](fg:color_purple bg:color_green)\
$nodejs\
$python\
$rust\
$golang\
$java\
$ruby\
$php\
[ ](fg:color_green)\
$line_break$character\
"""

palette = "gruvbox_dark"
command_timeout = 500

# Palettes
[palettes.gruvbox_dark]
color_fg0 = "#fbf1c7"
color_fg1 = "#181818"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_blue = "#458588"
color_aqua = "#689d6a"
color_green = "#98971a"
color_orange = "#d65d0e"
color_purple = "#b16286"
color_red = "#cc241d"
color_yellow = "#d79921"

[palettes.anysphere_dark]
color_fg0 = "#D6D6DD"
color_bg0 = "#181818"
color_bg1 = "#292929"
color_bg2 = "#3A3A3A"
color_blue = "#3A6DA0"
color_aqua = "#72D6D6"
color_green = "#73AD2B"
color_orange = "#BE9117"
color_purple = "#D3869B"
color_red = "#D64D5B"
color_yellow = "#EBC88D"

# User
[username]
show_always = true
format = "[ $user ]($style)"
style_user = "bg:color_orange fg:color_fg1"
style_root = "bg:color_orange fg:color_fg0"

# Directory
[directory]
style = "fg:color_fg1 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Git
[git_branch]
symbol = "git。"
style = "bg:color_aqua"
format = "[[ $symbol $branch ](fg:color_fg1 bg:color_aqua)]($style)"

[git_status]
style = "bg:color_aqua"
format = "[[($all_status$ahead_behind )](fg:color_fg1 bg:color_aqua)]($style)"

# Cloud Config
[aws]
symbol = "aws。"
style = "bg:color_blue"
format = "[ $symbol$profile:($region) ](fg:color_fg1 bg:color_blue)"

[gcloud]
symbol = "gcp。"
style = "bg:color_blue"
format = "[ $symbol$account(@$domain)(:$project)($region) ](fg:color_fg1 bg:color_blue)"

# Cluster Config
[kubernetes]
symbol = "k8s。"
style = "bg:color_purple"
format = "[ $symbol$context ](fg:color_fg1 bg:color_purple)"

[nodejs]
symbol = "js。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[python]
symbol = "py。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[rust]
symbol = "rs。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[golang]
symbol = "go。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[java]
symbol = "java。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[ruby]
symbol = "rb。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

[php]
symbol = "php。"
format = "[ $symbol($version) ](fg:color_fg1 bg:color_green)"

# Character
[character]
success_symbol = "[⌦](bold fg:color_green)"
error_symbol = "[⌦](bold fg:color_red)"

[line_break]
disabled = false
