[general]
import = [
    "~/.config/alacritty/keybindings.toml",
    # "~/.config/alacritty/catppuccin_mocha.toml",
    # "~/.config/alacritty/catppuccin_macchiato.toml",
]

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.98

[window.dimensions]
columns = 170
lines = 50

[window.padding]
x = 5
y = 7

[scrolling]
history = 100000
multiplier = 3

[font]
size = 13.0

[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"

[font.bold]
family = "ZedMono Nerd Font"
style = "Bold"

[font.italic]
family = "ZedMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "ZedMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"
