[tools]
awscli    = "latest"
argo      = "latest"
helm      = "latest"
kubectl   = "latest"
terraform = "latest"
tfsec     = "latest"
tflint    = "latest"
rust      = "latest"
go        = "latest"
pnpm      = "latest"
yarn      = "1.22"
bun       = "latest"
node      = "lts"
python    = "latest"
uv        = "latest"
gradle    = "latest"
java      = "21"
"npm:@opencode-ai/cli" = { version = "0.0.0-next-16502", bun_args = "--trust" }

[settings.npm]
package_manager = "bun"
