import = [
  "~/.config/alacritty/gruvbox_dark.toml",
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/tmux.toml",
]

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.98

[window.dimensions]
columns = 170
lines = 50

[window.padding]
x = 5
y = 7

[scrolling]
history = 100000
multiplier = 3

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 13.0

[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "On"
