# Colors {{{
# https://leanpub.com/the-tao-of-tmux/read#leanpub-auto-styling

BLACK="black"
BLUE="blue"
CYAN="cyan"
GREEN="green"
MAGENTA="magenta"
RED="red"
WHITE="white"
YELLOW="yellow"

BRIGHT_BLUE="brightblue"
BRIGHT_CYAN="brightcyan"
BRIGHT_GREEN="brightgreen"
BRIGHT_MAGENTA="brightmagenta"
BRIGHT_RED="brightred"
BRIGHT_WHITE="brightwhite"
BRIGHT_YELLOW="brightyellow"

# }}}

# Bindings {{{

# Reload the file with prefix r
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# Ensure that we can send Ctrl-A to other apps
bind C-a send-prefix

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Make splitting windows easier
bind-key v split-window -h
bind-key s split-window -v -b -p 20
bind-key _ split-window -v -p 20

# Moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Quick pane selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind-key - select-layout even-vertical
bind-key | select-layout even-horizontal

# Break pane out into new window
bind-key b break-pane -d

# Quickly switch between sessions
bind-key C-j choose-tree

# Break out new session based on current pane
bind-key C-b send-keys 'tat && exit' 'C-m'

# Open 30% terminal pane and run g function (g.fish)
bind-key g split-window -v -p 35 \; send-keys 'g' Enter

# }}}

# Settings {{{

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Setting the delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Tells tmux up front what shell to expect
set-option -g default-shell ${HOMEBREW_PREFIX}/bin/fish

# Enable mouse support
set-option -g mouse on

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Extend display time of status messages to 2 seconds
set-option -g display-time 2000

# Increase scroll limit
set-option -g history-limit 100000

# Display tmux session name in terminal title (instead of just "tmux")
set-option -g set-titles on

# }}}

# Window/Pane Appearance {{{

# set the color of the window list
setw -g window-status-style fg=$BLACK,bg=$BLUE

# set colors for the active window
setw -g window-status-current-style fg=$WHITE,bg=$BRIGHT_RED

# pane colors
set -g pane-border-style bg=default,fg=default
set -g pane-active-border-style bg=default,fg=$BLUE

# Tmux prompt colors
set -g message-style fg=$WHITE,bg=$BLACK

# Move status to the top
set-option -g status-position top

# }}}

# Status bar {{{

# Enable UTF-8 support in status bar
set -g status on

# Status bar settings
set -g status-left-length 60
set -g status-left "#[fg=$GREEN][#S] #[fg=$RED]w#I #[fg=$BLUE]p#P"
set -g status-right-length 60
set -g status-right " #[fg=$WHITE]%a, %b %d | %H:%M "
set -g status-interval 15
set -g status-justify centre

# Status bar background color.
set -g status-style bg=$BLACK

# }}}
