#!/bin/bash

# ----------------------------------------------------+
#         install asdf plugins and tools
# ----------------------------------------------------+

set -o errexit
set -o pipefail

TOOL_VERSIONS="home/.tool-versions"
source "scripts/commons.bash"

echo "# autogenerated from templates/asdf.*" >${TOOL_VERSIONS}
while read TOOL; do
  NAME=$(echo "${TOOL}" | awk {'print $1'})
  VERSION=$(echo "${TOOL}" | awk {'print $1'})
  REPOSITORY=$(echo "${TOOL}" | awk {'print $1'})
  asdf plugin add ${NAME} ${REPOSITORY} || true
  echo "${NAME} ${VERSION}" >>${TOOL_VERSIONS}
done <templates/asdf.personal
