#!/bin/bash

# ----------------------------------------------------+
#         install asdf plugins and tools
# ----------------------------------------------------+

set -o errexit
set -o pipefail

source "scripts/commons.bash"

TOOL_VERSIONS="home/tool-versions"
ALL_TOOLS="${SOURCE}/all-tools"
eval "$(${HOMEBREW_PREFIX}/bin/brew shellenv)"

if test -f "is_job"; then
  cat templates/asdf.job >> "${ALL_TOOLS}"
else
  cat templates/asdf.personal > "${ALL_TOOLS}"
fi

echo "# autogenerated from ~/.dotfiles/scripts/templates/asdf.*" >${TOOL_VERSIONS}
while read TOOL; do
  NAME=$(echo "${TOOL}" | awk {'print $1'})
  VERSION=$(echo "${TOOL}" | awk {'print $2'})
  REPOSITORY=$(echo "${TOOL}" | awk {'print $3'})
  asdf plugin add ${NAME} ${REPOSITORY} || true
  echo "${NAME} ${VERSION}" >>${TOOL_VERSIONS}
done <"${ALL_TOOLS}"

rm -rf "${ALL_TOOLS}"
